--- a/.github/workflows/build_test_wasm.yml
+++ b/.github/workflows/build_test_wasm.yml
@@ -123,4 +123,4 @@
         (github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name, 'CI:full'))
       run: |
-        ./ci.sh test -E 'bash_test'
+        ./ci.sh test -E 'bash_test'